/**
 * Generates src/icons/generated.ts from the vendored Phosphor SVGs in src/icons/svg.
 * Run `npm run icons` after adding or removing an SVG.
 *
 * Icons live in the repo (MIT, see src/icons/LICENSE) rather than as a runtime
 * dependency: nothing to keep in sync, and only the icons we use reach the bundle.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const svgDir = join(here, "..", "src", "icons", "svg");
const out = join(here, "..", "src", "icons", "generated.ts");

const entries = readdirSync(svgDir)
  .filter((f) => f.endsWith(".svg"))
  .sort()
  .map((file) => {
    const inner = readFileSync(join(svgDir, file), "utf8")
      .replace(/^[\s\S]*?<svg[^>]*>/, "")
      .replace(/<\/svg>\s*$/, "")
      .replace(/\s*fill="(?!none)[^"]*"/g, "")
      .replace(/stroke="#[0-9a-fA-F]{3,6}"/g, 'stroke="currentColor"')
      .trim();
    if (!inner) throw new Error(`Empty icon: ${file}`);
    return [file.replace(/\.svg$/, ""), inner];
  });

writeFileSync(
  out,
  `// GENERATED by scripts/build-icons.mjs — do not edit by hand.
// Source: Phosphor Icons (regular weight), vendored in src/icons/svg. MIT, see ./LICENSE.

export const ICON_PATHS = {
${entries.map(([n, d]) => `  ${JSON.stringify(n)}: ${JSON.stringify(d)},`).join("\n")}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`
);
console.log(`Generated ${entries.length} icons -> src/icons/generated.ts`);
