"""add_telemetry_logs_table

Revision ID: 1cf73f5ba3a0
Revises: c9d3e2b81f56
Create Date: 2026-07-11 09:28:30.511756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf73f5ba3a0'
down_revision: Union[str, Sequence[str], None] = 'c9d3e2b81f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_created_at'), 'telemetry_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_event_type'), 'telemetry_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_id'), 'telemetry_logs', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_user_id'), 'telemetry_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_logs_user_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_event_type'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_created_at'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    # ### end Alembic commands ###
