"""add broadcasts table

Revision ID: 54ef1913c988
Revises: b2c3d4e5f6a1
Create Date: 2026-07-03 10:36:57.724714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ef1913c988'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_admin_id'), 'broadcasts', ['admin_id'], unique=False)
    op.create_index(op.f('ix_broadcasts_id'), 'broadcasts', ['id'], unique=False)
    op.create_index(op.f('ix_broadcasts_status'), 'broadcasts', ['status'], unique=False)
    op.alter_column('game_history', 'game_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('game_history', 'white_player_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('game_history', 'black_player_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('game_history', 'white_elo_before',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_history', 'white_elo_after',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_history', 'black_elo_before',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_history', 'black_elo_after',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_history', 'total_moves',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('game_history', 'game_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'online'"))
    op.alter_column('game_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('game_history', 'ended_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'fee',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'completed'"))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('unlocked_lessons', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('unlocked_lessons', 'lesson_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('unlocked_lessons', 'unlocked_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_user_tasks_task_id'), 'user_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_user_tasks_user_id'), 'user_tasks', ['user_id'], unique=False)
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'false'"))
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'xp',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_elo'), 'users', ['elo'], unique=False)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    op.alter_column('xp_transactions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('xp_transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('xp_transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('xp_transactions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_index(op.f('ix_users_elo'), table_name='users')
    op.alter_column('users', 'preferred_language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'xp',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'false'"))
    op.drop_index(op.f('ix_user_tasks_user_id'), table_name='user_tasks')
    op.drop_index(op.f('ix_user_tasks_task_id'), table_name='user_tasks')
    op.alter_column('unlocked_lessons', 'unlocked_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('unlocked_lessons', 'lesson_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('unlocked_lessons', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('transactions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'completed'"))
    op.alter_column('transactions', 'fee',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('transactions', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.alter_column('game_history', 'ended_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('game_history', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('game_history', 'game_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'online'"))
    op.alter_column('game_history', 'total_moves',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('game_history', 'black_elo_after',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_history', 'black_elo_before',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_history', 'white_elo_after',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_history', 'white_elo_before',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_history', 'black_player_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('game_history', 'white_player_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('game_history', 'game_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_broadcasts_status'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_id'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_admin_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
