"""add_content_models

Revision ID: 5b106fd5041a
Revises: 859df7f35d7b
Create Date: 2026-07-15 08:31:17.633820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b106fd5041a'
down_revision: Union[str, Sequence[str], None] = '859df7f35d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Idempotent: guard on existence so the deploy-blocking `alembic upgrade
    # head` converges even if the tables were already created (create_all on
    # dev SQLite, manual repair) — see the 2026-07-15 crash-loop outage.
    conn = op.get_bind()
    tables = set(sa.inspect(conn).get_table_names())

    if 'lessons' not in tables:
        op.create_table('lessons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('difficulty', sa.String(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('xp_reward', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('lessons', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_lessons_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_lessons_slug'), ['slug'], unique=True)

    if 'puzzles' not in tables:
        op.create_table('puzzles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fen', sa.String(), nullable=False),
        sa.Column('solution', sa.String(), nullable=False),
        sa.Column('theme', sa.String(), nullable=False),
        sa.Column('difficulty', sa.String(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('xp_reward', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('puzzles', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_puzzles_id'), ['id'], unique=False)

    if 'lesson_steps' not in tables:
        op.create_table('lesson_steps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lesson_id', sa.Integer(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('fen', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('lesson_steps', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_lesson_steps_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_lesson_steps_lesson_id'), ['lesson_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_steps_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_steps_id'))

    op.drop_table('lesson_steps')
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzles_id'))

    op.drop_table('puzzles')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_slug'))
        batch_op.drop_index(batch_op.f('ix_lessons_id'))

    op.drop_table('lessons')
    # ### end Alembic commands ###
