"""add_gamification_achievements_themes

Revision ID: 859df7f35d7b
Revises: 1f113c29058b
Create Date: 2026-07-15 00:24:45.000205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859df7f35d7b'
down_revision: Union[str, Sequence[str], None] = '1f113c29058b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('requirement_type', sa.String(), nullable=True),
    sa.Column('requirement_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_achievements_id'), ['id'], unique=False)

    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('theme_type', sa.Enum('BOARD', 'PIECES', name='themetype'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_xp', sa.Integer(), nullable=True),
    sa.Column('css_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_themes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_themes_id'), ['id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievements_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('user_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'theme_id', name='uq_user_inventory_user_theme')
    )
    with op.batch_alter_table('user_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_inventory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_theme_id'), ['theme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_inventory_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_inventory_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_theme_id'))
        batch_op.drop_index(batch_op.f('ix_user_inventory_id'))

    op.drop_table('user_inventory')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievements_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievements_achievement_id'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_themes_id'))
        batch_op.drop_index(batch_op.f('ix_themes_code'))

    op.drop_table('themes')
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_id'))
        batch_op.drop_index(batch_op.f('ix_achievements_code'))

    op.drop_table('achievements')
    # ### end Alembic commands ###
